continuum/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views

app_name = 'continuum'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create_choice/$', views.create_choice, name='create_choice'),
    url(r'^view_choices/', views.view_choices, name='view_choices'),
    path('<int:choice_id>/view_choice_details/', views.view_choice_details, name='view_choice_details'),
    url(r'^cast_a_vote/$', views.cast_a_vote, name='cast_a_vote'),
    url(r'^create_question/$', views.create_question, name='create_question'),
    url(r'^cast_vote/$', views.cast_a_vote, name='cast_vote'),

    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('questions/latest/', views.index),
]

website/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('admin/', admin.site.urls),    
    url(r'^continuum/', include('continuum.urls')),
    url(r'^', include('continuum.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

continuum/models.py
from django.db import models
import django.utils.timezone as timezone

#This is the voting process
class Question(models.Model):
	question_text = models.CharField(max_length=256)
	pub_date = models.DateTimeField('date published', default=timezone.now())
	budget = models.FloatField(null=False)

	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		return self.pub_date >= timezone.now() - timezone.timedelta(days=1)

#This is the project choice
class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=256)
	description = models.CharField(max_length=512, default='No description provided')
	cost = models.FloatField()

class Votes(models.Model):
	process = models.ForeignKey(Question, on_delete=models.CASCADE)
	name = models.CharField(max_length=256, null=True)
	votes = models.CharField(max_length=256)

	def __repr__(self):
		return self.votes

	def get_vote_list(self):
		# 1: remove spaces.
		# 2: convert to list separated by comma.
		# 3: remove duplicates
		# 4: convert each to int.
		# 5: convert map obj to list
		return list(map(int, dict.fromkeys(self.votes.replace(' ', '').split(','))))

continuum/forms.py
from django import forms
from .models import Choice, Votes, Question



class create_choice_form(forms.ModelForm):

	class Meta:
		model = Choice
		fields = [ 'question', 'choice_text', 'description', 'cost']

class vote_form(forms.ModelForm):

	class Meta:
		model = Votes
		fields = [ 'name', 'process', 'votes' ]

class create_question_form(forms.ModelForm):
	class Meta:
		model = Question
		fields = ['question_text', 'budget']

continuum/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from .forms import *
from .models import *
from django.urls import reverse


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # output = ', '.join([q.question_text for q in latest_question_list])
    context = {
        'voting_processes': latest_question_list
    }
    return render(request, 'continuum/index.html', context)


def create_choice(request):
    form = create_choice_form(request.POST or None)
    processes = Question.objects.all().count()
    if form.is_valid():
        vote = form.save(commit=False)
        form.save()
        return render(request, 'continuum/index.html', {'message': 'Choice created!'})
    context = {
        'form': form,
        'voting_process': processes
    }
    return render(request, 'continuum/create_choice.html', context)


def create_question(request):
    form = create_question_form(request.POST or None)
    processes = Question.objects.all().count()
    context = {
        'form': form,
        'number_of_processes': processes
    }
    if form.is_valid():
        form.save()
        context['message'] = 'Voting process created!'
        return render(request, 'continuum/index.html', context)
    return render(request, 'continuum/create_voting_process.html', context)


def view_choices(request):
    choices = Choice.objects.all()
    count = Choice.objects.all().count()
    context = {
        'choices': choices,
        'count': count
    }
    return render(request, 'continuum/view_choices.html', context)


def view_choice_details(request, choice_id):
    choice = get_object_or_404(Choice, pk=choice_id)
    return render(request, 'continuum/view_choice_details.html', {'choice': choice})


def cast_a_vote(request):
    form = vote_form(request.POST or None)
    if form.is_valid():
        vote = form.save(commit=False)
        valid_choices = Choice.objects.filter(question_id=vote.process.id)
        valid_choice_ids = []
        for item in valid_choices:
            valid_choice_ids.append(item.id)
        try:
            # 1: remove spaces.
            # 2: convert to list separated by comma.
            # 3: remove duplicates
            # 4: convert each to int.
            # 5: convert map obj to list
            the_vote = list(map(int, dict.fromkeys(vote.votes.replace(' ', '').split(','))))
            if len(the_vote) != len(valid_choice_ids):
                return render(request, 'continuum/index.html', {
                    'error_message': 'Your vote length is {} and it should be {}. Please include all choices in your vote ordered by priority. Consider that duplicates are removed automatically.'.format(
                        len(the_vote), len(valid_choice_ids))})
            for item in the_vote:
                if item in valid_choice_ids:
                    pass
                else:
                    return render(request, 'continuum/index.html', {
                        'error_message': 'Invalid vote....... The format may be incorrect or the choices does not belongs to the selected voting process. HINT: process: {}. your vote: {}. valid votes {}'.format(
                            vote.process.id, the_vote, valid_choice_ids)})
            form.save()
            return render(request, 'continuum/index.html', {'message': 'Vote submited!'})
        except:
            render(request, 'continuum/index.html', {
                'error_message': 'Invalid vote.......<br>The format may be incorrect or the choices does not belongs to the selected voting process'})

    context = {
        'form': form
    }
    return render(request, 'continuum/cast_a_vote.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'continuum/detail.html', {'question': question})


def results(request, question_id):
    # The voting results are calculated each time the view is loaded, that allows to show real time results while a process is running and participants are voting.
    # In the other hand we save the raw vote to the db
    question = get_object_or_404(Question, pk=question_id)
    votes = Votes.objects.filter(process_id=question_id)
    choices = Choice.objects.filter(question_id=question.id)
    choice_list = {}
    #We create a dict of dicts with all choices and their performance. For each round when a choice wins, is deleted from this variable and sent to the results list
    for choice in choices: choice_list[str(choice.id)] = {'id': choice.id, 'votes': 0, 'cost': choice.cost,
                                                          'name': choice.choice_text}
    rounds = {}
    # create dict structure with all their indexes
    for i in range(0, len(choice_list)):
        rounds[str(i)] = []
    results = []
    expenses = 0 # Count the expenses to discard options with higher cost that the budget.
    # We have a list of votes, each vote is a list too, so we can traet it as a matrix, each column is a round of voting, so we iterate them vertically. We don't transpose, instead of that we use an iterative approach instead of a recursive one because of performance impact.
    # rounds of voting
    for i in range(0, len(choice_list)):
        try:
            for vote in votes:
                # sum the vote to the 'choice'
                choice_list[str(vote.get_vote_list()[i])]['votes'] += 1
                # add the vote to the round
                rounds[str(i)].append(vote.get_vote_list()[i])
            # sort dict by greatest number of votes
            round = sorted(choice_list, key=lambda x: choice_list[x]['votes'])[::-1]
            for item in round:
                # check budget
                tmp = expenses + choice_list[item]['cost']
                # if budget = ok, then apply the change
                if (question.budget - tmp >= 0):
                    expenses += choice_list[item]['cost']
                    # we have a winner, add it to results and delete from choice list, proceed with next round
                    results.append(choice_list[item])
                    del choice_list[item]
                    break
                else:
                    # winner choice not in budget, delete from choice list and proceed
                    del choice_list[item]
        # When we delete an element, we can have KeyError because we already assigned the range (of iteration)
        except KeyError: pass
    print(expenses)
    print(results)
    print(rounds)
    debug = []
    for item in list(rounds):
        debug.append(''.join(str(e) + ' ' for e in rounds[item]))
    context = {
        'results': results,
        'rounds': rounds,
        'debug': debug,
        'expenses': expenses,
        'question': question
    }
    return render(request, 'continuum/results.html', context)

continuum/templates/continuum/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Vote {% block title %}  {% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
</head>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'continuum:index' %}">
            <img src="/static/medusa.png" width="30" height="30" alt="">
            Dinámica de Proyectos
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{% url 'continuum:index' %}" class="nav-link"><span
                            class="glyphicon glyphicon-cd"
                            aria-hidden="true"></span>&nbsp;
                        Home</a></li>
                </li>
                <li class="nav-item">
                    <a href="{% url 'continuum:create_question' %}" class="nav-link"><span
                            class="glyphicon glyphicon-cd"
                            aria-hidden="true"></span>&nbsp;
                        1. Create Voting Process</a></li>
                </li>
                <li class="nav-item">
                    <a href="{% url 'continuum:create_choice' %}" class="nav-link"><span
                            class="glyphicon glyphicon-cd"
                            aria-hidden="true"></span>&nbsp;
                        2. Create Choice</a></li>
                </li>
                <li class="nav-item">
                    <a href="{% url 'continuum:view_choices' %}" class="nav-link"><span
                            class="glyphicon glyphicon-cd"
                            aria-hidden="true"></span>&nbsp;
                        View Choices</a></li>
                </li>
                <li class="nav-item">
                    <a href="{% url 'continuum:cast_vote' %}" class="nav-link"><span
                            class="glyphicon glyphicon-cd"
                            aria-hidden="true"></span>&nbsp;
                        3. Cast a Vote</a></li>
                </li>
{#                <li class="nav-item">#}
{#                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>#}
{#                </li>#}
            </ul>
        </div>
    </nav>
</header>

<body>
<main role="main" class="container">
    <div class="my-3 p-3 bg-white rounded shadow-sm">
        {% block body %}
        {% endblock %}
    </div>
</main>
</body>
</html>

continuum/templates/continuum/cast_a_vote.html
{% extends 'continuum/base.html' %}
{% block title %}Enter Project {% endblock %}

{% block body %}

    <div class="panel-body">
        <h6>Cast your votes</h6>
        <hr>
        <b>Example Vote</b>
        <p>Add your favorite project by project number separated by comma.<br><br><b>Example Vote:</b><br>
        <ul>
            <li><b>Name:</b> Juan Pérez</li>
            <li><b>Process: </b> Paseo fin de año</li>
            <li><b>Vote:</b> 1, 4, 5, 2</li>
        </ul>
        </p>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'continuum/form_template.html' %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">Submit</button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

continuum/templates/continuum/create_choice.html
{% extends 'continuum/base.html' %}
{% block title %}Create a Choice {% endblock %}

{% block body %}

    <h6 class="border-bottom border-gray pb-2 mb-0">Create a Choice</h6>

    <div class="media text-muted pt-3"></div>

    <div class="panel-body">
        {% if error_message %}
            <div class="alert alert-danger" role="alert">
                <p><strong>{{ error_message }}</strong></p>
            </div>
        {% endif %}
        {% if voting_process > 0 %}
            <ul>
                <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'continuum/form_template.html' %}
                    <div class="form-group">
                        <div class="col-sm">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>
            </ul>
        {% else %}
            <div class="alert alert-danger" role="alert">You can't insert a choice into a voting process because there
                is no voting process created. Please start
                by
                creating one by selecting the 'Create Voting Process' tab at the navigation
                bar. {{ voting_process }}</div>
        {% endif %}
    </div>




{% endblock %}

continuum/templates/continuum/create_project.html
{% extends 'continuum/base.html' %}
{% block title %}Enter Project {% endblock %}

{% block body %}

    <h6 class="border-bottom border-gray pb-2 mb-0">Create Project</h6>

    <div class="media text-muted pt-3"></div>

    <div class="panel-body">
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'continuum/form_template.html' %}
            <div class="form-group">
                <div class="col-sm">
                    <button type="submit" class="btn btn-success">Submit</button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

continuum/templates/continuum/create_voting_process.html
{% extends 'continuum/base.html' %}
{% block title %} Create Voting Process {% endblock %}

{% block body %}
    <h5 class="border-bottom border-gray pb-2 mb-0">Create a Voting Process</h5>
    {% if number_of_processes == 0 %}
        <div class="alert alert-danger" role="alert">
            <p><b>There are no voting processes...</b><br>Please start by creating one!</p>
        </div>
    {% else %}
        <p>Please fill this form to create a new voting process</p>
    {% endif %}
    <ul>
        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'continuum/form_template.html' %}
            <div class="form-group">
                <div class="col-sm">
                    <button type="submit" class="btn btn-success">Submit</button>
                </div>
            </div>
        </form>
    </ul>
{% endblock %}

continuum/templates/continuum/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'continuum:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>

continuum/templates/continuum/details_projects.html
{% extends 'continuum/base.html' %}
{% block title %} Project Details {% endblock %}

{% block body %}
{% for project in projects %}
{% if project.name == 'Proyecto 1' %}

	<a href="{% url 'continuum:entervote' project.id %}"><h1>{{ project.name }}</h1></a>
	<h1>{{ project.amount }}</h1>

{% endif %}

{% endfor %}
{% endblock %}

continuum/templates/continuum/enter_project.html
{% extends 'continuum/base.html' %}
{% block title %}Enter Project {% endblock %}

{% block body %}
<div class="panel-body">
	<h3>Add a New Project</h3>
    	{% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
        	{% csrf_token %}
            	{% include 'continuum/form_template.html' %}
                <div class="form-group">
                	<div class="col-sm-offset-2 col-sm-10">
                    	<button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>
        </form>
</div>

{% endblock %}

continuum/templates/continuum/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="row">
            <div class="col-sm">
                <span class="text-danger small">{{ field.errors }}</span>
            </div>
            <label class="control-label col-sm">{{ field.label_tag }}</label>
            <div class="col-sm-10">{{ field }}</div>
        </div>
    </div>
{% endfor %}

continuum/templates/continuum/index.html
{% extends 'continuum/base.html' %}
{% block title %} Home {% endblock %}
{% block body %}

    <div class="row">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="/static/team.jpg" class="d-block w-100" alt="...">
                </div>
            </div>
            <a class="carousel-control-prev" href="#nogo" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#nogo" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    {% if message %}
        <div class="row">
            <div class="col-sm">
                <div class="alert alert-success" role="alert">
                    {{ message }}
                </div>
            </div>
        </div>
    {% elif error_message %}
        <div class="row">
            <div class="col-sm">
                <div class="alert alert-danger" role="alert">
                    {{ error_message }}
                </div>
            </div>
        </div>
    {% elif voting_processes %}
        <div class="row">
            <div class="col-sm">
                <h4 class="border-bottom border-gray pb-2 mb-0">View Voting Processes</h4>
            </div>
        </div>
        <div class="row">
        <div class="col-sm">
            Sorting newest first, click to view results.
        </div>
        </div>
        {% for voting_process in voting_processes %}
            <div class="row">
                <div class="col-sm">
                    <div class="media text-muted pt-3">
                        <img src="/static/medusa.svg" height="32px" , width="32px">
                        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                            <strong class="d-block text-gray-dark">
                                                    <a href="{% url 'continuum:results' voting_process.id %}">
                                {{ voting_process.question_text.upper }}
                                                    </a>
                            </strong>
                            {{ voting_process.budget }}
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="alert alert-danger" role="alert">
            No voting processes are available, please create one by selecting the 'Create Voting Process' tab at the
            navigation bar.
        </div>
    {% endif %}
    </div>

    </div>
{% endblock %}

continuum/templates/continuum/results.html
{% extends 'continuum/base.html' %}
{% block title %} View Results {% endblock %}

{% block body %}
    <h6 class="border-bottom border-gray pb-2 mb-0">View Results for {{ question.question_text }}</h6>
    <p>Total budget: ${{ question.budget }}</p>
    <p>Total Expenses: ${{ expenses }}</p>
        {% for item in results %}
            <div class="media text-muted pt-3">
                <img src="/static/medusa.svg" height="32px" , width="32px">
                <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">

                        <b>
                            {{ item.votes }} votes for: {{ item.name.upper }}
                        </b>

                    ${{ item.cost }}
                </p>
            </div>
        {% endfor %}
    <hr>
    <b>Debug: </b>
Votes per round <br>
<ul>
{% for item in debug %}
    <li>{{ item }}</li>
{% endfor %}
</ul>
{% endblock %}

continuum/templates/continuum/view_choice_details.html
{% extends 'continuum/base.html' %}
{% block title %} View Choice details {% endblock %}

{% block body %}
    <h6 class="border-bottom border-gray pb-2 mb-0">Name: {{ choice.choice_text.upper }}</h6>
    <div class="media text-muted pt-3">
        <img src="/static/medusa.svg" height="32px" , width="32px">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <strong>Description: </strong>{{ choice.description.lower }}
        </p>
    </div>
    <h6>Cost:</h6>
    <ul>
        <li>{{ choice.cost }}</li>
    </ul>
{% endblock %}

continuum/templates/continuum/view_choices.html
{% extends 'continuum/base.html' %}
{% block title %} View Choices {% endblock %}

{% block body %}
    <h6 class="border-bottom border-gray pb-2 mb-0">View Choices</h6>
    {% if count == 0 %}
        <div class="alert alert-danger" role="alert">
            <b>There are no choices...</b><br>Please start by adding one by selecting 'Create Choice' in the navigation
            bar!
        </div>
    {% else %}
        {% for choice in choices %}
            <div class="media text-muted pt-3">
                <img src="/static/medusa.svg" height="32px" , width="32px">
                <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <a href="{% url 'continuum:view_choice_details' choice.id %}">
                        <b>
                            {{ choice.id }} -
                        </b>
                        {{ choice.choice_text.upper }}
                    </a>
                    ${{ choice.cost }} - {{ choice.question }}
                </p>
            </div>
        {% endfor %}
    {% endif %}

{% endblock %}

continuum/templates/continuum/view_projects.html
{% extends 'continuum/base.html' %}
{% block title %} Project Details {% endblock %}

{% block body %}
    <h6 class="border-bottom border-gray pb-2 mb-0">View Projects</h6>
    {% if projects.count == 0 %}
        <p><b>There are no projects...</b><br>Please start by adding one!</p>
    {% else %}
        {% for project in projects %}

            <div class="media text-muted pt-3">
                <img src="/static/medusa.svg" height="32px" , width="32px">
                <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <a href="{% url 'continuum:test' %}">
                        <strong class="d-block text-gray-dark">
                            {{ project.name }}
                        </strong>
                    </a>
                    {{ project.amount }}
                </p>
            </div>

            {#        {% if project.name == 'Proyecto 1' %}#}
            {#        {% endif %}#}

        {% endfor %}
    {% endif %}

{% endblock %}